services:
  app:
    build: .
    container_name: yt-app
    depends_on:
      - redis
      - db
    mem_limit: 512m
    cpus: 1.0
    command: ["-metrics=true", "-daily=false"]
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=pass
      - DB_NAME=metrics_db
      - YOUTUBE_API_KEYS=${YOUTUBE_API_KEYS}
    networks:
      - yt-network

  redis:
    image: redis:7
    container_name: yt-redis
    networks:
      - yt-network

  db:
    image: timescale/timescaledb:latest-pg14
    container_name: yt-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: metrics
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - yt-network

  grafana:
    image: grafana/grafana:latest
    container_name: yt-grafana
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - yt-network

volumes:
  db_data:
  grafana_data:

networks:
  yt-network:
    driver: bridge
